### ISSUE TITLE
Skill XP Bar an Text

### ISSUE THREAD

**Issue by ArchLupus** [BananaFructa/Apec#20]
With the skill xp bar, it switches between mining xp, farming xp, and carpentry xp just fine, but whenever i kill a mob, or cut down a tree, it doesnt display the combat, fishing, or foraging xp on the bar or text.
![image](https://user-images.githubusercontent.com/104752476/167068384-381d2b4d-8c36-4128-a4a1-01c09d65114a.png)

![image](https://user-images.githubusercontent.com/104752476/167068468-45ea59ad-3a4f-4ce0-ab2f-238774ed8f54.png)

**Comment by BananaFructa** [comment]
Can you toggle off apec (/apectoggle) and see if you can normally see the skill xp pop up?
