### ISSUE TITLE
skill xp still displays if turned off

### ISSUE THREAD

**Issue by DrDoctor13** [BananaFructa/Apec#24]
This is on the latest release in 1.8.9 forge

When skill XP is enabled:
![2022-07-31_02 08 36](https://user-images.githubusercontent.com/11695921/182012782-512a1d07-1726-4419-9c07-615494d60996.png)

When skill XP is disabled:
![2022-07-31_02 08 44](https://user-images.githubusercontent.com/11695921/182012788-0addd824-c839-41c9-9e0d-ba498b602b73.png)

I would like to hide it entirely, not just the bar

**Comment by BananaFructa** [comment]
Disable show skill text as well.
