### ISSUE TITLE
Scoreboard back and date off-screen

### ISSUE THREAD

**Issue by NowAlexIndustries** [BananaFructa/Apec#40]
No matter where I put the GUI element, the end of the date is always off-screen.

And now the scoreboard is back for some reason.

![Time GUI element is bottom middle](https://github.com/BananaFructa/Apec/assets/159421272/3c270065-6f89-42fc-96ad-eb7235577af3)

**Comment by wisefries** [comment]
I've found that if you have both Apec and SkyHanni, the vanilla scoreboard will be forced on. SkyHanni has its own Scoreboard (/sh, navigate to GUI > Custom Scoreboard) If this is disabled, the vanilla scoreboard will show even though Apec disables it. To fix this, you must choose whether to use Apec's or SkyHanni's custom scoreboards. To use only Apec's scoreboard, enable the custom scoreboard in SH's config, and drag all lines to the trash bin (see photo.)

![Screenshot 2024-04-18 153409](https://github.com/BananaFructa/Apec/assets/93115856/08f4b017-e49f-418b-884d-fbddcaedac71)


Consider making a backup of SkyHannis config before doing so. (.minecraft/config/skyhanni folder)
To "disable" Apec's scoreboard (there is no toggle), you will probably need to move it to the top of the screen so it is no longer visible.

**Comment by NowAlexIndustries** [comment]
Thx i also found this solution. Do you know anything about the date being off screen no where i put it?

**Comment by j10a1n15** [comment]
This issue no longer is relevant as of [0.27 Beta 17](https://github.com/hannibal002/SkyHanni/releases/tag/0.25.Beta.17)
