### ISSUE TITLE
/effects menu invisible

### ISSUE THREAD

**Issue by Dreamtrailtv** [BananaFructa/Apec#8]
I tried to open the /effects menu, but it was invisible.
After I disabled this mod the menu was shown again. 
I also tested to disable NotEnoughUpdates then the menu was also displayed again.

Mods:
1.8.9.Danker.s.Skyblock.Mod.-.1.8.4
AutoGG-4.0.3 (1.8.9)
Autotip-3.0.1 [1.8-1.12.2]
Cowlection-1.8.9-0.12.0
LabyMod-3
NotEnoughUpdates-1.7.2-REL
OptiFine 1.8.9 HD U L5
SkyblockAddons-1.8.9-1.5.4
SkyBlockcatia-1.8.9-1.0.15

The screenshot shows what is displayed.
below the not enough updates menu is displayed but not the inventory of the effects.
![unknown](https://user-images.githubusercontent.com/51512219/104069710-d82bdf00-5205-11eb-8690-52926404143b.png)
![image](https://user-images.githubusercontent.com/51512219/104069909-f691da80-5205-11eb-9570-85f83adef3cc.png)

**Comment by BananaFructa** [comment]
This bug is known to happen and will be repaired in the upcoming version, a fix for now would be to Enable the setting "Show tab effect". If you need any further help reopen the issue.
