### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PPojat** [BananaFructa/Apec#9]
A couple days ago I installed Apec again (before I used 1.2) and now its just not working, the gui is broken. When I toggle it it just hides my normal gui and does nothing other than clears my chat for some odd reason. Any explinations why?
Off: ![2021-01-22_17 10 31](https://user-images.githubusercontent.com/77846473/105508223-cef64400-5cd4-11eb-9cd0-e31bb3da8a5f.png)

On: ![2021-01-22_17 10 37](https://user-images.githubusercontent.com/77846473/105508256-d9184280-5cd4-11eb-9fbb-d501a2d6711a.png)

It might be another mod, so if any of these mods can't be used with Apec?
![Näyttökuva 2021-01-22 171347](https://user-images.githubusercontent.com/77846473/105508595-39a77f80-5cd5-11eb-9581-aaac58afcf4d.jpg)

**Comment by BananaFructa** [comment]
Remove you current version of sidebar and install the revamp which you can find [here](http://www.mediafire.com/file/gkzsovw2gjjuw3d/%255B1.8.9%255D_Sidebar_Mod_Revamp.jar/file)
